# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [
    "kvm-intel"
    # "v4l2loopback"
  ];
  # boot.extraModulePackages = with config.boot.kernelPackages; [
  #   v4l2loopback
  # ];
  # boot.extraModprobeConfig = ''
  #   options v4l2loopback devices=1 video_nr=1 card_label="OBS Cam" exclusive_caps=1
  # '';

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/a9152a2b-054c-498c-a016-27720aae387e";
    fsType = "btrfs";
    options = [
      "subvol=/rootfs"
      "compress=zstd"
      "rw"
      "relatime"
      "ssd"
      "discard=async"
      "space_cache=v2"
      "commit=120"
    ];
  };
  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/a9152a2b-054c-498c-a016-27720aae387e";
    fsType = "btrfs";
    options = [
      "subvol=/home"
      "compress=zstd"
      "rw"
      "relatime"
      "ssd"
      "discard=async"
      "space_cache=v2"
      "commit=120"
    ];
  };
  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/a9152a2b-054c-498c-a016-27720aae387e";
    fsType = "btrfs";
    options = [
      "subvol=/nix"
      "compress=zstd"
      "noatime"
      "ssd"
      "discard=async"
      "space_cache=v2"
      "commit=120"
    ];
  };

  fileSystems."/mnt/data" = {
    device = "/dev/disk/by-uuid/84470fd7-7316-441a-b3f3-6ec553f98772";
    fsType = "btrfs";
    options = [
      "subvol=/data"
      "compress=zstd"
      "rw"
      "relatime"
      "ssd"
      "discard=async"
      "space_cache=v2"
      "commit=120"
    ];
  };
  fileSystems."/mnt/data/personal" = {
    device = "/dev/disk/by-uuid/84470fd7-7316-441a-b3f3-6ec553f98772";
    fsType = "btrfs";
    options = [
      "subvol=/personal"
      "compress=zstd"
      "rw"
      "relatime"
      "ssd"
      "discard=async"
      "space_cache=v2"
      "commit=120"
    ];
  };
  fileSystems."/mnt/data/work" = {
    device = "/dev/disk/by-uuid/84470fd7-7316-441a-b3f3-6ec553f98772";
    fsType = "btrfs";
    options = [
      "subvol=/work"
      "compress=zstd"
      "rw"
      "relatime"
      "ssd"
      "discard=async"
      "space_cache=v2"
      "commit=120"
    ];
  };
  fileSystems."/mnt/data/misc" = {
    device = "/dev/disk/by-uuid/84470fd7-7316-441a-b3f3-6ec553f98772";
    fsType = "btrfs";
    options = [
      "subvol=/misc"
      "compress=zstd"
      "rw"
      "relatime"
      "ssd"
      "discard=async"
      "space_cache=v2"
      "commit=120"
    ];
  };
  # fileSystems."/mnt/data/snapshots" = {
  #   device = "/dev/disk/by-uuid/84470fd7-7316-441a-b3f3-6ec553f98772";
  #   fsType = "btrfs";
  #   options = [
  #     "subvol=/snapshots"
  #     "compress=zstd"
  #     "rw"
  #     "relatime"
  #     "ssd"
  #     "discard=async"
  #     "space_cache=v2"
  #     "commit=120"
  #   ];
  # };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/2FC3-4011";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  # swapDevices = [
  #   {
  #     device = "/mnt/data/sys/swapfile";
  #     size = 12 * 1024;
  #     randomEncryption.enable = false;
  #   }
  # ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
